### ISSUE TITLE
latest version on npmjs?

### ISSUE THREAD

**Issue by dbvcode** [escwdev/oanda-node-api#10]
Hi @escwdev 
is it just me or is the npmjs version a bit older then the code here?

**Comment by escwdev** [comment]
I haven't done much with this in quite some time, but the last changes probably weren't published to npm.

I'm going to try and review and integrate the commits and add any other small changes that I can see on quick review in the next few days. After that I can publish the newest version to npm.

**Comment by dbvcode** [comment]
I'm playing around with it to integrate it with my project.
Since the work is already done in your lib, I'll make a wrapper for it with typescript and most likely RxJS.
But given that I'm in an early stage of the approach I could also fork it and convert it into a TS library with types, especially if you don't have time to maintain it much. I don't expect it to be a lot of work to convert it as you have done the work already.

Let me know your plans with the project.

**Comment by escwdev** [comment]
The recent 0.1.0 update has been published to NPM.
