### ISSUE TITLE
Transactions endpoint bug?

### ISSUE THREAD

**Issue by maximusign** [escwdev/oanda-node-api#3]
Hi there,

Thanks for all your work on this package! It's the best one out there by far. 

As I was integrating the transactions end point, I think I found a bug.

In this endpoint: https://github.com/escwdev/oanda-node-api/blob/master/lib/endpoints/transactions.js

I think this line:   

`let url = this.accountURL + `/transactions/idrange` + formatQuery(options)`

Should be:   

`let url = this.accountURL + `/transactions/idrange` + this.formatQuery(options)`

as I get an error that formatQuery is not defined otherwise. That said, once I correct that, I'm now getting this error. Any ideas? 

(node:19345) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (/Users/ep/Documents/ft/Node/Vertical/node_modules/oanda-node-api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/ep/Documents/ft/Node/Vertical/node_modules/oanda-node-api/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/Users/ep/Documents/Forextrader/Node/Vertical/node_modules/oanda-node-api/node_modules/axios/lib/adapters/http.js:191:11)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:19345) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19345) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by escwdev** [comment]
Thanks maximusign.

To be honest I haven't used this library in awhile (though I may be getting back to it) so can't say for sure. Looking at the other endpoints on that page, and without looking over Oanda's docs, it may be a missing `/` after idrange.

I'm a bit busy but I'll try and add the `this` fix and test with the backslash.

Sorry for the late response too, this didn't pop up in my feed and got sent to an old email

**Comment by escwdev** [comment]
Included in the 0.1.x update.
